---

- name: create screen configuration
  become: true
  ansible.builtin.template:
    src: "screenrc.j2"
    dest: "{{ screen_conf_file }}"
    owner: "root"
    group: "root"
    mode: "0644"

...
